In [1]:
import pandas as pd

In [5]:
data = pd.read_csv("student_data.csv")
data.head()

   StudentID   Name  Gender   Age  Department  Marks  Attendance        City
0          1   Amit    Male  20.0    Computer   78.0        85.0        Pune
1          2  Priya  Female  21.0          IT   88.0        90.0      Mumbai
2          3  Rahul    Male  19.0  Mechanical   67.0        75.0      Nashik
3          4  Sneha  Female  22.0    Computer   92.0        95.0        Pune
4          5  Akash    Male  20.0       Civil   55.0        60.0  Aurangabad

In [6]:
data

    StudentID    Name  Gender   Age  Department  Marks  Attendance        City
0           1    Amit    Male  20.0    Computer   78.0        85.0        Pune
1           2   Priya  Female  21.0          IT   88.0        90.0      Mumbai
2           3   Rahul    Male  19.0  Mechanical   67.0        75.0      Nashik
3           4   Sneha  Female  22.0    Computer   92.0        95.0        Pune
4           5   Akash    Male  20.0       Civil   55.0        60.0  Aurangabad
5           6    Neha  Female  21.0          IT   73.0        80.0      Mumbai
6           7   Rohan    Male  23.0  Mechanical   49.0        65.0      Nagpur
7           8   Kajal  Female  20.0    Computer   81.0        88.0        Pune
8           9   Arjun    Male  22.0       Civil   60.0        70.0      Nashik
9          10   Pooja  Female  19.0          IT   77.0        85.0      Mumbai
10         11   Vikas    Male   NaN    Computer   85.0        90.0        Pune
11         12  Anjali  Female  21.0         NaN   91.0        92.0      Nagpur
12         13   Karan    Male  20.0       Civil    NaN        78.0  Aurangabad
13         14   Meena  Female  22.0  Mechanical   69.0         NaN      Nashik
14         15  Deepak    Male  21.0          IT   74.0        82.0         NaN

In [7]:
data.tail()

    StudentID    Name  Gender   Age  Department  Marks  Attendance        City
10         11   Vikas    Male   NaN    Computer   85.0        90.0        Pune
11         12  Anjali  Female  21.0         NaN   91.0        92.0      Nagpur
12         13   Karan    Male  20.0       Civil    NaN        78.0  Aurangabad
13         14   Meena  Female  22.0  Mechanical   69.0         NaN      Nashik
14         15  Deepak    Male  21.0          IT   74.0        82.0         NaN

In [8]:
data.isnull()

    StudentID   Name  Gender    Age  Department  Marks  Attendance   City
0       False  False   False  False       False  False       False  False
1       False  False   False  False       False  False       False  False
2       False  False   False  False       False  False       False  False
3       False  False   False  False       False  False       False  False
4       False  False   False  False       False  False       False  False
5       False  False   False  False       False  False       False  False
6       False  False   False  False       False  False       False  False
7       False  False   False  False       False  False       False  False
8       False  False   False  False       False  False       False  False
9       False  False   False  False       False  False       False  False
10      False  False   False   True       False  False       False  False
11      False  False   False  False        True  False       False  False
12      False  False   False  False       False   True       False  False
13      False  False   False  False       False  False        True  False
14      False  False   False  False       False  False       False   True

In [9]:
data.isnull().sum()

StudentID     0
Name          0
Gender        0
Age           1
Department    1
Marks         1
Attendance    1
City          1
dtype: int64

In [10]:
data.isna()

    StudentID   Name  Gender    Age  Department  Marks  Attendance   City
0       False  False   False  False       False  False       False  False
1       False  False   False  False       False  False       False  False
2       False  False   False  False       False  False       False  False
3       False  False   False  False       False  False       False  False
4       False  False   False  False       False  False       False  False
5       False  False   False  False       False  False       False  False
6       False  False   False  False       False  False       False  False
7       False  False   False  False       False  False       False  False
8       False  False   False  False       False  False       False  False
9       False  False   False  False       False  False       False  False
10      False  False   False   True       False  False       False  False
11      False  False   False  False        True  False       False  False
12      False  False   False  False       False   True       False  False
13      False  False   False  False       False  False        True  False
14      False  False   False  False       False  False       False   True

In [11]:
data.notnull()

    StudentID  Name  Gender    Age  Department  Marks  Attendance   City
0        True  True    True   True        True   True        True   True
1        True  True    True   True        True   True        True   True
2        True  True    True   True        True   True        True   True
3        True  True    True   True        True   True        True   True
4        True  True    True   True        True   True        True   True
5        True  True    True   True        True   True        True   True
6        True  True    True   True        True   True        True   True
7        True  True    True   True        True   True        True   True
8        True  True    True   True        True   True        True   True
9        True  True    True   True        True   True        True   True
10       True  True    True  False        True   True        True   True
11       True  True    True   True       False   True        True   True
12       True  True    True   True        True  False        True   True
13       True  True    True   True        True   True       False   True
14       True  True    True   True        True   True        True  False

In [12]:
data.notnull().sum()

StudentID     15
Name          15
Gender        15
Age           14
Department    14
Marks         14
Attendance    14
City          14
dtype: int64

In [13]:
data.describe()

       StudentID        Age      Marks  Attendance
count  15.000000  14.000000  14.000000   14.000000
mean    8.000000  20.785714  74.214286   81.071429
std     4.472136   1.188313  13.186115   10.469474
min     1.000000  19.000000  49.000000   60.000000
25%     4.500000  20.000000  67.500000   75.750000
50%     8.000000  21.000000  75.500000   83.500000
75%    11.500000  21.750000  84.000000   89.500000
max    15.000000  23.000000  92.000000   95.000000

In [17]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   StudentID   15 non-null     int64
 1   Name        15 non-null     str
 2   Gender      15 non-null     str
 3   Age         14 non-null     float64
 4   Department  14 non-null     str
 5   Marks       14 non-null     float64
 6   Attendance  14 non-null     float64
 7   City        14 non-null     str
dtypes: float64(3), int64(1), str(4)
memory usage: 1.1 KB

In [19]:
data.dtypes

StudentID       int64
Name              str
Gender            str
Age           float64
Department        str
Marks         float64
Attendance    float64
City              str
dtype: object

In [20]:
data.shape

(15, 8)

In [21]:
data.columns

Index(['StudentID', 'Name', 'Gender', 'Age', 'Department', 'Marks',
       'Attendance', 'City'],
      dtype='str')

In [22]:
data.ndim

2

In [30]:
data = data.dropna()
data

   StudentID   Name  Gender   Age  Department  Marks  Attendance        City
0          1   Amit    Male  20.0    Computer     78        85.0        Pune
1          2  Priya  Female  21.0          IT     88        90.0      Mumbai
2          3  Rahul    Male  19.0  Mechanical     67        75.0      Nashik
3          4  Sneha  Female  22.0    Computer     92        95.0        Pune
4          5  Akash    Male  20.0       Civil     55        60.0  Aurangabad
5          6   Neha  Female  21.0          IT     73        80.0      Mumbai
6          7  Rohan    Male  23.0  Mechanical     49        65.0      Nagpur
7          8  Kajal  Female  20.0    Computer     81        88.0        Pune
8          9  Arjun    Male  22.0       Civil     60        70.0      Nashik
9         10  Pooja  Female  19.0          IT     77        85.0      Mumbai

In [28]:
data['Marks'] = data['Marks'].astype(int)

In [33]:
data.dtypes

StudentID       int64
Name              str
Gender            str
Age           float64
Department        str
Marks           int64
Attendance    float64
City              str
dtype: object

In [8]:
data = pd.read_csv("student_dtat")

NameError: name 'data' is not defined

In [5]:
data["Gender"].replace({"Female":0, "Male":1}, inplace=True)

NameError: name 'data' is not defined

In [6]:
data

NameError: name 'data' is not defined